import type { Metadata } from "next";
import "./globals.css";
import { Footer, Nav } from "@/components";

export const metadata: Metadata = {
  title: "Alpha_AutoNation",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
